spring:
  application:
    name: client-service

# Config Eureka
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # ID of the instance
    preferIpAddress: true # Use IP address instead of hostname
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
